apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otel-lgtm.fullname" . }}
  labels:
    {{- include "otel-lgtm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "otel-lgtm.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "otel-lgtm.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
            - containerPort: 4317
            - containerPort: 4318




