apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-lgtm.fullname" . }}
  labels:
    {{- include "otel-lgtm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.port }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}
  selector:
    app: {{ include "otel-lgtm.name" . }}
