apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "spicedb-operator.fullname" . }}-edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  {{- include "spicedb-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - authzed.com
  resources:
  - spicedbclusters
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - authzed.com
  resources:
  - spicedbclusters/status
  verbs:
  - update
