apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "spicedb-operator.fullname" . }}-view
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  {{- include "spicedb-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - authzed.com
  resources:
  - spicedbclusters
  verbs:
  - get
  - list
  - watch
