apiVersion: v2
name: spicedb
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: postgresql
    version: 14.0.0
    repository: https://charts.bitnami.com/bitnami