# spicedb-cluster/helm/values.yaml
nameOverride: "spicedb"
fullnameOverride: "spicedb"

ingress:
  enabled: false
  tls: true
  tlsSecretName: spicedb-tls
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    cert-manager.io/cluster-issuer: "zerossl-issuer"
  hosts:
    - host: spicedb.localhost
      paths:
        - /
image:
  repository: ghcr.io/authzed/spicedb
  tag: v1.40.1