apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "spicedb-cluster.fullname" . }}
  labels:
    {{- include "spicedb-cluster.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  rules:
    - host: spicedb.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "spicedb-cluster.fullname" . }}
                port:
                  number: 80
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - spicedb.localhost
      secretName: {{ .Values.ingress.tlsSecretName }}
  {{- end }}