apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: spicedb-cert
  namespace: spicedb
spec:
  secretName: spicedb-tls
  issuerRef:
    name: zerossl-issuer
    kind: ClusterIssuer
  commonName: spicedb.localhost
  dnsNames:
    - spicedb.localhost
#  keyAlgorithm: rsa
#  keySize: 2048
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days before expiration
---
apiVersion: v1
kind: Secret
metadata:
  name: spicedb-secret
  namespace: spicedb
type: Opaque
data:
  grpc-preshared-key: c29tZWtleQ==