apiVersion: v1
kind: Secret
metadata:
  name: spicedb-config-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  preshared_key: c3BpY2VkYi1wcmUtc2hhcmVkLWtleQ==
  datastore_engine: progres
  datastore_uri: postgres://postgres:postgres@spicedb-postgres-postgresql.spicedb-postgres.svc.cluster.local:5432/spicedb